# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{snapmon}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ryan Stout2"]
  s.date = %q{2010-02-15}
  s.description = %q{Provides an interface to configure monitoring via snapmon.com from a config file.}
  s.email = %q{help@snapmon.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "app/controllers/snapmon_controller.rb",
     "config/routes.rb",
     "generators/snapmon_config/USAGE",
     "generators/snapmon_config/snapmon_config_generator.rb",
     "generators/snapmon_config/templates/snapmon.yml",
     "init.rb",
     "install.rb",
     "lib/capistrano.rb",
     "lib/snapmon.rb",
     "lib/snapmon/recipes.rb",
     "lib/snapmon_setup.rb",
     "recipes/snapmon.rb",
     "snapmon.gemspec",
     "tasks/snapmon_tasks.rake",
     "test/snapmon_test.rb",
     "test/test_helper.rb",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/ryanstout/snapmon}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Makes monitoring your app easy}
  s.test_files = [
    "test/snapmon_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

